In [1]:
import re;
text = 'Hello123, World!'
listWord = list(re.findall(r'\w+', text))
for word in listWord:
    print(word)

Hello123
World


In [2]:
import re;
text = 'Hello123, World!085400'
lisNum = list(re.findall(r'\d+', text))
for num in lisNum:
    print(num)

123
085400


In [11]:
#匹配以chen开头的字符串
import re;
text = 'chenran wanghai zhangsan lisi wangwu zhaoliu chenlin chenhai chenjian'
nameOfchen = list(re.findall(r'chen\w+',text))
for name in nameOfchen:
    print(name)

chenran
chenlin
chenhai
chenjian


In [ ]:
#匹配次数
import re;
text = 'hello 123 hi 4567 hey 89'
#*匹配0次或多次
print('匹配0次或多次：\n')
print(list(re.findall(r'\d*',text)))
print('匹配1次或多次：\n')
print(list(re.findall(r'\d+',text)))
print('精确匹配n次:')
print(list(re.findall(r'\d{2}',text)))
print('精确匹配2-4次：')
print(list(re.findall(r'\d{2,4}',text)))

In [21]:
#字符集和范围
import re;
text = 'Hello123, World!085400'
print('匹配abc中的任意一个字母:\n',re.findall(r'[abcee]',text))
#匹配以Hello开头，以数字结尾的字符串
print('匹配以Hello开头，以数字结尾的字符串:\n',re.findall(r'^Hello\d+$',text))
#匹配以Hello开头，以数字结尾的字符串，中间有任意字符
print('匹配以Hello开头，以数字结尾的字符串，中间有任意字符:\n',re.findall(r'^Hello.*\d+$',text))
#匹配以Hello开头，以数字结尾的字符串，中间有任意字符，但是数字不能为0
print('匹配以Hello开头，以数字结尾的字符串，中间有任意字符，但是数字不能为0:\n',re.findall(r'^Hello.*[1-9]\d*$',text))
#匹配以Hello开头，以数字结尾的字符串，中间有任意字符，但是数字不能为0
print('匹配以Hello开头，以数字结尾的字符串，中间有任意字符，但是数字不能为0:\n',re.findall(r'^Hello.*[1-9]\d*$',text))


匹配abc中的任意一个字母:
 ['e']


In [29]:
#找到符合模式的文本然后进行替换
import re;
text = '我是陈燃，我今年24岁，我来自中国，我来自南华大学!'
textOfsub = re.sub(r'南华大学','郑州轻工业大学',text)
print(textOfsub)

我是陈燃，我今年24岁，我来自中国，我来自郑州轻工业大学!


In [30]:
#split的用法
text = 'Hello,World,Python,Java,C++'
print(re.split(r',',text))

['Hello', 'World', 'Python', 'Java', 'C++']


In [ ]:
# 用于求解非线性方程组的根，即找到函数输出值为零的输入值。
from scipy.optimize import root
from math import cos

def eqn(x):
  return x**2 -2

# hybr只会寻找离初始猜测值最近的根。
myroot1 = root(eqn, -1)
myroot2 = root(eqn, 1)
print(myroot1)
print('******************************************')
print(root(eqn, 1))

In [ ]:
from scipy.optimize import minimize


def eqn(x):
    return x**2 + x + 2

mymin = minimize(eqn, 0, method='BFGS')
print(mymin)

In [3]:
def f(x):
    return x**2 + x + 2

# 在[-2, 2]范围内寻找最小值
result = minimize(f, x0=0, bounds=[(-2, 2)])
print(f"最小值点: {result.x[0]}")
print(f"最小值: {result.fun}")

最小值点: -0.5000000004916901
最小值: 1.75


In [4]:
# sparse: 稀疏矩阵及相关程序
import scipy as sp
import numpy as np
dense = np.array([[1, 0, 0, 2], [0, 4, 1, 0], [0, 0, 5, 0]])
sparse = sp.sparse.coo_array(dense)
print(sparse)
print('****************************************')
print(sparse.todense())

  (0, 0)	1
  (0, 3)	2
  (1, 1)	4
  (1, 2)	1
  (2, 2)	5
****************************************
[[1 0 0 2]
 [0 4 1 0]
 [0 0 5 0]]
